server:
  port: 3002
  servlet:
    context-path: /api/frauds-checking

spring:
  application:
    name: fraud-checking-service
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://localhost:5432/microservices
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
  main:
    banner-mode: off
