server:
  port: 3002
  servlet:
    context-path: /api/frauds-checking

spring:
  application:
    name: fraud-checking-service
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://postgres:5432/microservices
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
  main:
    banner-mode: off
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-discovery-service:8761/eureka
