version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: microservices
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./sql/schemas.sql:/docker-entrypoint-initdb.d/1-schemas.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - "5432:5432"
    networks:
      - postgres

  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - zipkin

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management-alpine
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root

networks:
  postgres:
    driver: bridge
  zipkin:
    driver: bridge
  rabbitmq:
    driver: bridge

volumes:
  postgres:
  rabbitmq:
