server:
  port: 3000
  servlet:
    context-path: /api/customers

spring:
  application:
    name: customer-service
  datasource:
    username: root
    password: root
    url: jdbc:postgresql://postgres:5432/microservices
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create
  main:
    banner-mode: off
  zipkin:
    base-url: http://zipkin:9411
  rabbitmq:
    addresses: amqp://rabbitmq:5672
    username: root
    password: root

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-discovery-service:8761/eureka

application:
  amqp:
    rabbitmq:
      exchange:
        name: internal.exchange
      queue:
        name: notification.queue
      routing-key:
        internal-notification: internal.notification.routing-key
